pipeline {
    options {
        // set a timeout of 30 minutes for this pipeline
        timeout(time: 30, unit: 'MINUTES')
    }
    agent {
      node {
        label 'master'
      }
    }

    stages {

        stage('stage 1') {
            steps {
                script {
                    openshift.withCluster() {
                        openshift.withProject() {
                                echo "stage 1: using project: ${openshift.project()} in cluster ${openshift.cluster()}"
                        }
                    }
                }
            }
        }

        stage('question') {
            steps {

                script {
                timeout(time: 60, unit: 'MINUTES') {
                      input message: "Move to stage 3?"
                  }
                  }
             }
        

                script {
                  sh '''
                      echo hello
                  '''
            }

        }
        // TODO: ADD AN APPROVAL STAGE

        stage('stage 3') {
            steps {
                sh 'echo hello from stage 3!. This is the last stage...'
            }
        }

    }
}
